### PR TITLE
package as a snap

### LINKED ISSUE #174: Pack as snap
I find it hard to install `gitless` from sources. [snaps](https://docs.snapcraft.io/build-snaps/python) look like a viable alternative to `pip`.

### PR DESCRIPTION
**Pull request by techtonik**
Closes #174.

### CODE REVIEW

**Comment by techtonik** [comment]
Almost done. Now need to expose the binary and strip size a bit.

**Comment by techtonik** [comment]
* [ ] expose executable
* [ ] make sure can access dirs in home
* [ ] make sure can access any current dir
* [ ] setup edge autodeployment
* [ ] write build manual

**Comment by techtonik** [comment]
The snap can now be installed and run in `--devmode` as `gitless.gl`. So this is a working prototype that could be then enhanced according to checklist above.

**Comment by spderosso** [comment]
@techtonik thank you!

**Comment by louisremi** [comment]
For snap newbies like me, the complete command to install the package from snap **currently** is:
`snap install --edge --devmode gitless`

**Comment by louisremi** [comment]
@techtonik after installing the snap and rebooting my computer, `gl` still returns `command not found`. Is there an obvious step I missed? Thanks :-)

**Pull request merged**
